# Generated by Django 4.2.4 on 2023-09-03 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_is_active'),
    ]

    operations = [
    ]
