# Generated by Django 4.2.4 on 2023-09-03 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_auto_20230903_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_change_mailing_is_active', 'Can change mailing is active'), ('can_block_user', 'Can block user')], 'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
    ]
