# Generated by Django 4.2.4 on 2023-09-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_change_mailing_is_active', 'Can change mailing is active')], 'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
    ]
